author: NextInfinity
commands: 
  0: 
    description: "Changes the player's gamemode to Survival."
    permission: simplegm.use
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  1: 
    description: "Changes the player's gamemode to Creative."
    permission: simplegm.use
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  2: 
    description: "Changes the player's gamemode to Adventure."
    permission: simplegm.use
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  3: 
    description: "Changes the player's gamemode to Spectator."
    permission: simplegm.use
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  simplegm:
    description: "Shows basic plugin info and command usage."
    permission: simplegm.info
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
description: "Simple Gamemode Changer."
main: org.jamescraft.simplegamemode.SimpleGamemode
name: SimpleGamemode
permissions: 
  simplegm.*: 
    children: 
      simplegm.use: true
      simplegm.use.others: true
      simplegm.info: true
    default: op
    description: "Gives access to all SimpleGamemode commands."           
  simplegm.use: 
    default: op
    description: "Lets the player gamemode themself"
  simplegm.use.others: 
    default: op
    description: "Lets the player gamemode others"  
  simplegm.info:
    default: true
    description: "Gives access to use /simplegm"
version: 3.0
website: infnet.co
