author: xGIx
commands: 
  0: 
    description: "Changes the player's gamemode to Survival."
    permission: simplegm.survival
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  1: 
    description: "Changes the player's gamemode to Creative."
    permission: simplegm.creative
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  2: 
    description: "Changes the player's gamemode to Adventure."
    permission: simplegm.adventure
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
  simplegm:
    description: "Shows basic plugin info and command usage."
    permission: simplegm.info
    permission-message: "You do not have permission for this command!"
    usage: Type /simplegm for help
description: "Simple Gamemode Changer."
main: org.jamescraft.simplegamemode.SimpleGamemode
name: SimpleGamemode
permissions: 
  simplegm.*: 
    children: 
      simplegm.adventure.*: true
      simplegm.creative.*: true
      simplegm.survival.*: true
      simplegm.info: true
    default: op
    description: "Gives access to all SimpleGamemode commands."
  simplegm.adventure.*:
    children:
      simplegm.adventure: true
      simplegm.adventure.others: true
    default: op
    description: "Lets the player adventure mode themself and others"     
  simplegm.creative.*:
    children:
      simplegm.creative: true
      simplegm.creative.others: true
    default: op
    description: "Lets the player creative mode themself and others"   
  simplegm.survival.*:
    children:
      simplegm.survival: true
      simplegm.survival.others: true
    default: op
    description: "Lets the player survival mode themself and others"           
  simplegm.adventure: 
    default: op
    description: "Lets the player adventure mode themself"
  simplegm.creative: 
    default: op
    description: "Lets the player creative mode themself"
  simplegm.survival: 
    default: op
    description: "Lets the player survival mode themself"
  simplegm.adventure.others: 
    default: op
    description: "Lets the player adventure mode others"
  simplegm.creative.others: 
    default: op
    description: "Lets the player creative mode others"
  simplegm.survival.others: 
    default: op
    description: "Lets the player survival mode others"    
  simplegm.info:
    default: true
    description: "Gives access to use /simplegm"
<<<<<<< HEAD
version: 2.1
website: geninfinity.com
=======
version: 2.0
website: rn-mc.com
>>>>>>> c4571d2c68e4d19b9e17cd3db99238514a47f161
