author: NextInfinity
commands: 
  0: 
    description: "Changes the player's gamemode to Survival."
    usage: /0 [player]
  1: 
    description: "Changes the player's gamemode to Creative."
    usage: /1 [player]
  2: 
    description: "Changes the player's gamemode to Adventure."
    usage: /2 [player]
  3: 
    description: "Changes the player's gamemode to Spectator."
    usage: /3 [player]
description: "Simple Gamemode Changer."
main: net.theinfinitymc.simplegamemode.SimpleGamemode
name: SimpleGamemode
permissions: 
  simplegm.*: 
    children: 
      simplegm.use: true
      simplegm.use.others: true
    default: op
    description: "Includes all SimpleGM permissions"
  simplegm.use: 
    default: op
    description: "Allows the player to change their own gamemode"
  simplegm.use.others: 
    default: op
    description: "Allows the player to change the gamemode of other players"
version: 5.0
